apiVersion: v1
kind: Secret
metadata:
  name: datadog-secret
  namespace: datadog
type: Opaque
stringData:
  api-key: "a77c4759f11fb82ae9fe4b9d31b0e85b"
  app-key: "d423f2ab5c7c7750b9d524e1354fc33a5bc522e6"
