datadog:
  # As chaves ficam em um Secret no namespace do release do Datadog.
  apiKeyExistingSecret: datadog-secret
  appKeyExistingSecret: datadog-secret
  site: us5.datadoghq.com
  dogstatsd:
    useHostPort: true
    nonLocalTraffic: true

  # Necessário para Minikube (TLS do kubelet não verificado)
  kubelet:
    tlsVerify: false

  # Habilitar APM/Traces
  apm:
    enabled: true
    
  # Logs
  logs:
    enabled: true
    containerCollectAll: true

# Agent DaemonSet
agents:
  enabled: true
  rbac:
    create: true
    serviceAccountName: datadog-agent

# Cluster Agent (importante para métricas!)
clusterAgent:
  enabled: true
  rbac:
    create: true
    serviceAccountName: datadog-cluster-agent
  admissionController:
    enabled: true
    mutateUnlabelled: false  
  # Metrics Provider (necessário para HPA)
  metricsProvider:
    enabled: true
    useDatadogMetrics: true
    service:
      type: ClusterIP
      port: 8443
