apiVersion: datadoghq.com/v1alpha1
kind: DatadogMetric
metadata:
  name: app-php-scaling
  namespace: app-php
spec:
##  query: avg:container.cpu.limit{service:app-php}
  query: sum:php.request.count{service:app-php}.rollup(sum,60)