apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-php-hpa-datadog
  namespace: app-php
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-php
  minReplicas: 1
  maxReplicas: 5
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 3
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
  metrics:
  - type: External
    external:
      metric:
        name: datadogmetric@app-php:app-php-latency
      target:
        type: AverageValue
        averageValue: "250M"