apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-php-hpa-datadog
  namespace: app-php
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-php
  minReplicas: 1
  maxReplicas: 5
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
        - type: Percent
          value: 50
          periodSeconds: 15
  metrics:
  - type: External
    external:
      metric:
        name: datadogmetric@app-php:app-php-scaling
      target:
        type: Value
        value: "100"